# Generated by Django 5.2.7 on 2026-02-16 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeblock',
            name='location',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
