# Generated by Django 5.2.7 on 2026-02-09 13:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(max_length=15, validators=[django.core.validators.RegexValidator('^(?:0|\\+?44)(?:\\d\\s?){9,10}$')]),
        ),
    ]
