# Generated by Django 5.2.7 on 2026-02-16 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scheduler", "0002_timeblock_location"),
    ]

    operations = [
        migrations.AddField(
            model_name="timeblock",
            name="duration",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="timeblock",
            name="is_fixed",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="timeblock",
            name="time_of_day_preference",
            field=models.CharField(
                blank=True,
                choices=[
                    ("morning", "Morning"),
                    ("afternoon", "Afternoon"),
                    ("evening", "Evening"),
                ],
                max_length=20,
                null=True,
            ),
        ),
    ]
