# Generated by Django 5.2.7 on 2026-02-21 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0003_timeblock_duration_timeblock_is_fixed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeblock',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
