# Generated by Django 5.2.7 on 2026-02-24 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scheduler", "0004_timeblock_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="timeblock",
            name="end_time",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="timeblock",
            name="start_time",
            field=models.TimeField(blank=True, null=True),
        ),
    ]
