# Generated by Django 5.2.7 on 2026-02-24 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0004_timeblock_description'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='dayplan',
            constraint=models.UniqueConstraint(fields=('user', 'date'), name='unique_dayplan_per_user_date'),
        ),
    ]
