# Generated by Django 5.2.7 on 2026-02-24 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scheduler", "0005_alter_timeblock_end_time_alter_timeblock_start_time"),
    ]

    operations = [
        migrations.AddField(
            model_name="timeblock",
            name="name",
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
