# Generated by Django 5.2.7 on 2026-02-24 21:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0005_dayplan_unique_dayplan_per_user_date'),
        ('scheduler', '0006_note'),
        ('scheduler', '0006_timeblock_name'),
    ]

    operations = [
    ]
