# Generated by Django 5.2.7 on 2026-02-25 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0007_merge_20260224_2146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeblock',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
