# Generated by Django 5.2.7 on 2026-02-25 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0008_alter_timeblock_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeblock',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
    ]
