# Generated by Django 5.2.7 on 2026-03-09 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("scheduler", "0009_alter_timeblock_description"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="timeblock",
            name="duration",
        ),
        migrations.RemoveField(
            model_name="timeblock",
            name="is_fixed",
        ),
        migrations.RemoveField(
            model_name="timeblock",
            name="time_of_day_preference",
        ),
    ]
