# Generated by Django 5.2.7 on 2026-03-21 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0010_remove_timeblock_duration_remove_timeblock_is_fixed_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
    ]
