# Generated by Django 5.2.7 on 2026-03-23 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0010_remove_timeblock_duration_remove_timeblock_is_fixed_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
        migrations.AddField(
            model_name='timeblock',
            name='timezone',
            field=models.CharField(default='UTC', max_length=50),
        ),
    ]
