# Generated by Django 5.2.7 on 2026-03-21 18:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0011_alter_user_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalendarSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('source_url', models.CharField(max_length=1000)),
                ('is_active', models.BooleanField(default=True)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calendar_subscriptions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ImportedCalendarEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_event_uid', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imported_events', to='scheduler.calendarsubscription')),
                ('time_block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imported_calendar_events', to='scheduler.timeblock')),
            ],
        ),
        migrations.AddConstraint(
            model_name='calendarsubscription',
            constraint=models.UniqueConstraint(fields=('user', 'source_url'), name='unique_calendar_subscription_per_user_url'),
        ),
        migrations.AddConstraint(
            model_name='importedcalendarevent',
            constraint=models.UniqueConstraint(fields=('subscription', 'external_event_uid'), name='unique_imported_event_per_subscription_uid'),
        ),
    ]
