# Generated by Django 5.2.7 on 2026-03-24 18:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0011_alter_user_options_timeblock_timezone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message='Enter a valid UK phone number.', regex='^(?:0|\\+?44)(?:\\d\\s?){9,10}$')]),
        ),
    ]
