# Generated by Django 5.2.7 on 2026-03-22 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0012_calendarsubscription_importedcalendarevent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeblock',
            name='name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
