# Generated by Django 5.2.7 on 2026-03-24 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0011_alter_user_options_timeblock_timezone'),
        ('scheduler', '0013_alter_timeblock_name'),
    ]

    operations = [
    ]
