# Generated by Django 5.2.7 on 2026-03-24 23:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0012_alter_user_phone_number'),
        ('scheduler', '0014_merge_20260324_1526'),
    ]

    operations = [
    ]
