# Generated by Django 5.2.7 on 2026-04-02 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0015_merge_20260324_2307'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeblock',
            name='completed_at',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
