# Generated by Django 5.2.7 on 2026-04-04 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0016_timeblock_completed_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeblock',
            name='pinned',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='timeblock',
            name='pinned_at',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
