# Generated by Django 5.2.7 on 2026-04-13 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scheduler", "0017_timeblock_pinned_timeblock_pinned_at"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="dayplan",
            name="unique_dayplan_per_user_date",
        ),
        migrations.AddConstraint(
            model_name="dayplan",
            constraint=models.UniqueConstraint(
                fields=("user", "date"), name="unique_day_plan_per_user_date"
            ),
        ),
    ]
